export const lightColors = {
    background: '#FFFDF9',
    buttonColor: '#F98A21',
    secondary: '#2F80ED',
    text: '#1C1C1C',
    subtext: '#4A4A4A',
    border: '#D9D9D9',
    buttonBorder: '#F98A21',
    success: '#27AE60',
    error: '#EB5757',
    muted: '#8C8C8C',
    buttonText: '#FFFFFF',
    tabBarBackground: '#FFFFFF',
    deckGradient: ["#fff8f0", "#ffe0c3", "#f9b97a"],
    appbar: '#ffffff',
    title: '#000000',
    libraryTab: '#fff8f0',
    blurView: 'rgba(255,255,255,0.85)',
    blurViewShadow: '#F98A21',
    cards: '#ffffff',
    orWhite: '#F98A21',
    actionButton: '#fff8f0',
    inProgressBar: '#d9d9d9',
    headText: '#F98A21',
    divider: '#FFFFFF',
    // Kart renkleri
    cardBackground: '#FFF8F0',
    cardQuestionText: '#1C1C1C',
    cardAnswerText: '#4A4A4A',
    cardDivider: '#F98A21',
    cardButtonBackground: '#ffffff',
    progressBar: '#ffe0c3',
    foldedCorner: '#f9b97a',
    progressBarSwipe: '#ffe0c3',
    cardBorder: '#E9E9E9',
    shadowColor: "#000",
    shadowOpacity: 0.08,   // Hafif gölge
    shadowRadius: 8,       // Gölge yumuşaklığı
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
    iconBackground: 'rgba(0,0,0,0.05)',
};

export const darkColors = {
    background: '#1C1C1C',
    buttonColor: '#F98A21',
    secondary: '#2F80ED', 
    text: '#FFFFFF',
    subtext: '#E0E0E0',
    border: '#7A7A7A',
    buttonBorder: '#DDDDDD',
    success: '#27AE60',
    error: '#EB5757',
    muted: '#BDBDBD',
    buttonText: '#FFFFFF',
    tabBarBackground: '#1C1C1C',
    deckGradient: ['#2C2C2C', '#4A3E2D', '#F98A21'],
    appbar: '#1C1C1C',
    title: '#FFFFFF',
    libraryTab: '#2C2C2C',
    blurView: 'rgba(0,0,0,0.4)',
    blurViewShadow: 'rgba(0,0,0,0.1)',
    cards: '#1E1E1E',
    orWhite: '#FFFFFF',
    actionButton: '#FEFEFE',
    inProgressBar: '#dddddd',
    headText: '#F0F0F0',
    divider: '#F98A21',
    // Kart renkleri
    cardBackground: '#2C2C2C',
    cardQuestionText: '#FFFFFF',
    cardAnswerText: '#E0E0E0',
    cardDivider: '#F98A21',
    cardButtonBackground: '#2C2C2C',
    progressBar: '#4A4A4A',
    foldedCorner: '#F98A21',
    progressBarSwipe: '#FFFFFF',
    cardBorder: '#333333',
    shadowColor: "#000",
    shadowOpacity: 0.3,    // Light Mode'a göre biraz daha belirgin
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
    iconBackground: 'rgba(255, 255, 255, 0.1)',

};